{
    'name': 'Dellyman Package Management',
    'version': '1.0.0',
    'summary': 'Standalone package + batch management and Dellyman connector (no Inventory dependency)',
    'description': """Manage package batches, scan tracking IDs, sync status (placeholder) with Dellyman and track deliveries — designed for Odoo 18. No dependency on Inventory.""" ,
    'author': 'Generated by ChatGPT',
    'license': 'LGPL-3',
    'category': 'Warehouse/Delivery',
    'depends': ['base', 'barcodes', 'web'],
    'data': [
        'data/sequence_data.xml',
        'views/package_batch_views.xml',
        'views/package_order_views.xml',
        'views/package_location_views.xml',
        'views/menu.xml',
        'security/ir.model.access.csv'
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
